Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ on:
 
 jobs:
   merge-translate-into-master:
-    name: Merge Translate into Master
+    name: Merge translate into master
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout master branch
@@ -18,10 +18,26 @@ jobs:
         with:
           ref: master
 
+      - name: Checkout translate branch
+        uses: actions/checkout@v4
+        with:
+          ref: translate
+
       - name: Attempt to merge translate into master
+        id: merge_step
         run: |
-          git merge origin/translate --no-ff --no-commit || echo "Merge failed, continuing with master"
+          git merge translate --no-ff --no-commit || echo "Merge failed, continuing with master"
         continue-on-error: true
+
+      - name: Check if merge was successful
+        id: merge_check
+        run: |
+          if ! git status | grep -q 'Changes to be committed'; then
+            echo "Merge was unsuccessful"
+            exit 1  # Explicitly fail this step
+          else
+            echo "Merge was successful"
+          fi
 
   run_linters:
     name: Run Linters
